2024-05-12 20:01:22.335163 - __init__.py: ERR: No Arguements Given
